apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${APP}-secret
  namespace: apps
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: ${APP}-${OWNER}-${ENVIRONMENT}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ${APP}-${OWNER}-${ENVIRONMENT}